### ISSUE TITLE
gogensig:invalid receiver type ..Filename

### ISSUE THREAD

**Issue by luoliwoshang** [goplus/llcppg#44]
`llcppg.cfg`
```
{
	"name": "sqlite3",
	"cflags": "$(pkg-config --cflags sqlite3)",
	"libs": "$(pkg-config --libs sqlite3)",
	"include": ["sqlite3.h"],
	"trimPrefixes": ["sqlite3_"],
	"cplusplus": false
}
```
` llcppg -v` got
```bash
2024/12/13 17:48:20 NewFuncDecl: &{sqlite3_open16}
2024/12/13 17:48:20 NewFuncDecl: &{sqlite3_open_v2}
2024/12/13 17:48:20 NewFuncDecl: &{sqlite3_uri_parameter}
panic: -: invalid receiver type ..Filename (..Filename is a pointer type)

goroutine 1 [running]:
github.com/goplus/gogen.(*Package).NewFuncDecl(0x0?, 0x0?, {0x140000abc71, 0xc}, 0x1400000d5c0?)
        /Users/zhangzhiyang/go/pkg/mod/github.com/goplus/gogen@v1.16.3/func.go:139 +0x114
github.com/goplus/llcppg/cmd/gogensig/convert.(*Package).newFuncDeclAndComment(0x140004da570, 0x14000370600, 0x14000353270?, 0x14000353270)
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/convert/package.go:169 +0x74
github.com/goplus/llcppg/cmd/gogensig/convert.(*Package).NewFuncDecl(0x140004da570, 0x14000353270)
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/convert/package.go:211 +0x224
github.com/goplus/llcppg/cmd/gogensig/convert.(*AstConvert).VisitFuncDecl(0x101099520?, 0x14000353270)
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/convert/convert.go:81 +0x24
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).visitFuncDecl(...)
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/visitor/ast_visitor.go:60
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).visitNode(0x140000b25f0?, {0x1010a39a0?, 0x14000353270?})
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/visitor/ast_visitor.go:33 +0x94
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).Visit(0x14000133b88?, {0x10108e680?, 0x1400030a280?})
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/visitor/ast_visitor.go:49 +0x78
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocVisitorManager).Visit(0x14000499c50?, {0x10108e680, 0x1400030a280}, {0x14000026d80, 0x2a}, {0x1400048adf0, 0x9}, 0x60?)
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/processor/processor.go:23 +0x94
github.com/goplus/llcppg/cmd/gogensig/convert/basic.ConvertProcesser.func1(0x1010a9940?)
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/convert/basic/basic.go:38 +0x44
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocFileSetProcessor).visitFile(0x1400020e240, {0x14000026d80, 0x2a}, {0x14000499c20?, 0x1, 0x1})
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/processor/processor.go:77 +0x250
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocFileSetProcessor).ProcessFileSet(0x1400020e240, {0x14000499c20?, 0x1, 0x1})
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/processor/processor.go:95 +0x144
main.main()
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/cmd/gogensig/gogensig.go:94 +0x3bc
panic: exit status 2

goroutine 1 [running]:
main.check(...)
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/llcppg.go:99
main.main()
        /Users/zhangzhiyang/Documents/Code/goplus/llcppg/llcppg.go:94 +0x428
```

**Comment by tsingbx** [comment]
libtasn1有同样问题

**Comment by tsingbx** [comment]
llcppgtest apr-util-1
```
invalid receiver type []interface{} ([]interface{} is not a defined type)
```
