### ISSUE TITLE
panic: Fts5PhraseIter redefined

### ISSUE THREAD

**Issue by tsingbx** [goplus/llcppg#58]
the error log file of running 'llcppgtest sqlite3' command :

```
2024/12/18 13:21:43 Fts5PhraseIter redefined
panic: Fts5PhraseIter redefined

goroutine 1 [running]:
log.Panicln({0xc00039d858?, 0xe?, 0xc000461e60?})
	/usr/local/Cellar/go@1.21/1.21.13/libexec/src/log/log.go:446 +0x5a
github.com/goplus/llcppg/cmd/gogensig/convert.substObj(0xc00007e360, 0x0?, {0xc0007e71a0, 0xe}, {0x13ae878?, 0xc000a4fd10})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/convert/type.go:417 +0x1d9
github.com/goplus/llcppg/cmd/gogensig/convert.(*Package).NewTypeDecl(0xc00067eac0, 0xc000a84420)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/convert/package.go:248 +0x465
github.com/goplus/llcppg/cmd/gogensig/convert.(*AstConvert).VisitStruct(0x18?, 0xc00039da00?, 0x2?, 0xc000a84420)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/convert/convert.go:99 +0x2e
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).visitStruct(...)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/visitor/ast_visitor.go:88
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).visitTypeDecl(0xc000a60520?, 0xc0006be180?)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/visitor/ast_visitor.go:73 +0x71
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).visitNode(0xc000a05b60?, {0x12cab40?, 0xc000a84420?})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/visitor/ast_visitor.go:35 +0x54
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).Visit(0xc000a05b58?, {0x12b5de0?, 0xc000654320?})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/visitor/ast_visitor.go:49 +0x6b
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocVisitorManager).Visit(0xc000061200?, {0x12b5de0, 0xc000654320}, {0xc00050e6f0, 0x27}, {0xc0000c69d3, 0x9}, 0x1?)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/processor/processor.go:23 +0xa6
github.com/goplus/llcppg/cmd/gogensig/convert/basic.ConvertProcesser.func1(0x12cd900?)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/convert/basic/basic.go:38 +0x39
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocFileSetProcessor).visitFile(0xc000578200, {0xc00050e6f0, 0x27}, {0xc00007b200?, 0x3, 0x4})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/processor/processor.go:77 +0x2ce
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocFileSetProcessor).ProcessFileSet(0xc000578200, {0xc00007b200?, 0x3, 0x4})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/processor/processor.go:95 +0x17d
main.main()
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/gogensig.go:94 +0x4cf
panic: exit status 2
```

[err.log](https://github.com/user-attachments/files/18175440/err.log)
and the llcppg.cfg:
```json
{
	"name": "sqlite3",
	"cflags": "$(pkg-config --cflags sqlite3)",
	"libs": "$(pkg-config --libs sqlite3)",
	"include": [
		"sqlite3.h",
		"sqlite3ext.h"
	],
	"deps": null,
	"trimPrefixes": [],
	"cplusplus": false
}
```

**Comment by tsingbx** [comment]
llcppgtest libcares 有同样问题
