### ISSUE TITLE
panic: underlying type must not be nil

### ISSUE THREAD

**Issue by tsingbx** [goplus/llcppg#61]
```json
{
	"name": "gnutls",
	"cflags": "$(pkg-config --cflags gnutls)",
	"libs": "$(pkg-config --libs gnutls)",
	"include": [
		"nettle/blowfish.h",
		"nettle/memxor.h",
		"gnutls/tpm.h",
		"nettle/yarrow.h",
		"p11-kit/iter.h",
		"nettle/eddsa.h",
		"nettle/gcm.h",
		"gnutls/gnutlsxx.h",
		"nettle/base64.h",
		"nettle/sha2.h",
		"nettle/cfb.h",
		"nettle/rsa.h",
		"idn2.h",
		"nettle/ecc-curve.h",
		"nettle/knuth-lfib.h",
		"p11-kit/p11-kit.h",
		"p11-kit/uri.h",
		"gnutls/compat.h",
		"nettle/nist-keywrap.h",
		"nettle/pbkdf2.h",
		"nettle/serpent.h",
		"nettle/siv-cmac.h",
		"nettle/cbc.h",
		"nettle/ctr.h",
		"gnutls/dtls.h",
		"gnutls/pkcs7.h",
		"nettle/pss-mgf1.h",
		"gnutls/system-keys.h",
		"nettle/balloon.h",
		"nettle/nettle-meta.h",
		"gnutls/urls.h",
		"nettle/cmac.h",
		"gnutls/x509.h",
		"gnutls/ocsp.h",
		"nettle/ccm.h",
		"nettle/bignum.h",
		"nettle/drbg-ctr.h",
		"nettle/sha.h",
		"nettle/umac.h",
		"gnutls/pkcs12.h",
		"nettle/twofish.h",
		"nettle/base16.h",
		"nettle/cast128.h",
		"nettle/realloc.h",
		"nettle/ripemd160.h",
		"nettle/sexp.h",
		"libtasn1.h",
		"nettle/eax.h",
		"nettle/hkdf.h",
		"nettle/ocb.h",
		"nettle/pkcs1.h",
		"nettle/pss.h",
		"p11-kit/pin.h",
		"nettle/poly1305.h",
		"nettle/sha3.h",
		"nettle/sm4.h",
		"gnutls/x509-ext.h",
		"gnutls/crypto.h",
		"gnutls/dane.h",
		"gnutls/openpgp.h",
		"gnutls/self-test.h",
		"nettle/gostdsa.h",
		"gnutls/pkcs11.h",
		"nettle/chacha-poly1305.h",
		"nettle/des.h",
		"nettle/siv-gcm.h",
		"nettle/arctwo.h",
		"nettle/memops.h",
		"nettle/nettle-types.h",
		"nettle/version.h",
		"nettle/dsa.h",
		"gnutls/gnutls.h",
		"gnutls/socket.h",
		"nettle/arcfour.h",
		"nettle/curve25519.h",
		"nettle/md5.h",
		"nettle/curve448.h",
		"nettle/sm3.h",
		"nettle/camellia.h",
		"nettle/macros.h",
		"nettle/md4.h",
		"nettle/asn1.h",
		"nettle/dsa-compat.h",
		"nettle/md2.h",
		"nettle/md5-compat.h",
		"p11-kit/deprecated.h",
		"nettle/aes.h",
		"nettle/chacha.h",
		"gnutls/abstract.h",
		"nettle/pgp.h",
		"nettle/xts.h",
		"nettle/gosthash94.h",
		"nettle/salsa20.h",
		"nettle/streebog.h",
		"nettle/buffer.h",
		"nettle/ecdsa.h",
		"nettle/sha1.h",
		"p11-kit/pkcs11.h",
		"p11-kit/pkcs11x.h",
		"nettle/ecc.h",
		"nettle/hmac.h",
		"p11-kit/remote.h"
	],
	"deps": null,
	"trimPrefixes": [],
	"cplusplus": false
}
```

run 'llcppgtest gnutls'
2024/12/18 16:09:23 NewFuncDecl nettle_blowfish_set_key Fail: symbol not found
2024/12/18 16:09:23 NewFuncDecl nettle_blowfish128_set_key Fail: symbol not found
2024/12/18 16:09:23 NewFuncDecl nettle_blowfish_encrypt Fail: symbol not found
2024/12/18 16:09:23 NewFuncDecl nettle_blowfish_decrypt Fail: symbol not found
2024/12/18 16:09:23 NewFuncDecl nettle_blowfish_bcrypt_hash Fail: symbol not found
2024/12/18 16:09:23 NewFuncDecl nettle_blowfish_bcrypt_verify Fail: symbol not found
2024/12/18 16:09:23 NewFuncDecl wait Fail: type wait already defined in /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/sys/wait.h,include path: sys/wait.h
panic: underlying type must not be nil

goroutine 1 [running]:
go/types.(*Named).SetUnderlying(0xc006f9a0e0, {0x0, 0x0})
	/usr/local/Cellar/go@1.21/1.21.13/libexec/src/go/types/named.go:437 +0xe5
github.com/goplus/gogen.(*TypeDecl).InitType(0xc00ccae1f0, 0xc000396000, {0x13aafa0?, 0xc006f9a150?}, {0x0, 0x0, 0x0})
	/Users/xulingjiao/go/pkg/mod/github.com/goplus/gogen@v1.16.3/type_var_and_const.go:114 +0x25d
github.com/goplus/llcppg/cmd/gogensig/convert.(*Package).NewTypedefDecl(0xc000596ac0, 0xc005779c00)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/convert/package.go:336 +0x87e
github.com/goplus/llcppg/cmd/gogensig/convert.(*AstConvert).VisitTypedefDecl(0x13adef8?, 0xc005779c00)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/convert/convert.go:126 +0x28
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).visitTypedefDecl(...)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/visitor/ast_visitor.go:106
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).visitNode(0x3?, {0x12caba0?, 0xc005779c00?})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/visitor/ast_visitor.go:39 +0xba
github.com/goplus/llcppg/cmd/gogensig/visitor.(*BaseDocVisitor).Visit(0xc00013e6f0?, {0x12b5de0?, 0xc0057c3f90?})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/visitor/ast_visitor.go:49 +0x6b
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocVisitorManager).Visit(0xc000063200?, {0x12b5de0, 0xc0057c3f90}, {0xc000146b40, 0x36}, {0xc000014b30, 0xf}, 0x1?)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/processor/processor.go:23 +0xa6
github.com/goplus/llcppg/cmd/gogensig/convert/basic.ConvertProcesser.func1(0x12cd900?)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/convert/basic/basic.go:38 +0x39
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocFileSetProcessor).visitFile(0xc00003bf00, {0xc004ea81c0, 0x36}, {0xc005886000?, 0xe0e, 0xf55})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/processor/processor.go:77 +0x2ce
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocFileSetProcessor).visitFile(0xc00003bf00, {0xc004e6f400, 0x36}, {0xc005886000?, 0xe0e, 0xf55})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/processor/processor.go:74 +0x287
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocFileSetProcessor).visitFile(0xc00003bf00, {0xc000146ac0, 0x33}, {0xc005886000?, 0xe0e, 0xf55})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/processor/processor.go:74 +0x287
github.com/goplus/llcppg/cmd/gogensig/processor.(*DocFileSetProcessor).ProcessFileSet(0xc00003bf00, {0xc005886000?, 0xe0e, 0xf55})
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/processor/processor.go:95 +0x17d
main.main()
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/cmd/gogensig/gogensig.go:94 +0x4cf
panic: exit status 2

goroutine 1 [running]:
main.check(...)
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/llcppg.go:99
main.main()
	/Users/xulingjiao/Documents/GitHub/tsingbx-llcppg/llcppg.go:94 +0x42c
llcppgtest run [gnutls] finished!

**Comment by tsingbx** [comment]
llcppgtest libzstd 有同样问题

**Comment by luoliwoshang** [comment]
在我的电脑上，问题是来自于typdef 一个枚举类型导致的panic

```bash
2024/12/24 09:17:55 NewFuncDecl: &{pwritev} is a function of system header file
2024/12/24 09:17:55 SetCurFile: compat.go File in Current Package: true
2024/12/24 09:17:55 NewTypedefDecl: &{gnutls_connection_end_t}
2024/12/24 09:17:55 NewTypedefDecl: &{gnutls_cipher_algorithm}
panic: underlying type must not be nil

goroutine 1 [running]:
go/types.(*Named).SetUnderlying(0x1400816bab0, {0x0, 0x0})
	/Users/zhangzhiyang/golang/go1.20.4/src/go/types/named.go:435 +0xf4
github.com/goplus/gogen.(*TypeDecl).InitType(0x1400fc4b9a0, 0x140000ca540, {0x102c469c0?, 0x1400816bb20?}, {0x0, 0x0, 0x0})
	/Users/zhangzhiyang/go/pkg/mod/github.com/goplus/gogen@v1.16.3/type_var_and_const.go:114 +0x1b0
```
```c
typedef enum gnutls_cipher_algorithm {
	GNUTLS_CIPHER_UNKNOWN = 0,
	GNUTLS_CIPHER_NULL = 1,
	GNUTLS_CIPHER_ARCFOUR_128 = 2,
	GNUTLS_CIPHER_3DES_CBC = 3,
	GNUTLS_CIPHER_AES_128_CBC = 4,
	GNUTLS_CIPHER_AES_256_CBC = 5,
	GNUTLS_CIPHER_ARCFOUR_40 = 6,
} gnutls_cipher_algorithm_t;
```

**Comment by luoliwoshang** [comment]
最小复现配置
```json
{
	"name": "gnutls",
	"cflags": "$(pkg-config --cflags gnutls)",
	"libs": "$(pkg-config --libs gnutls)",
	"include": [
		"gnutls/gnutls.h",
		"gnutls/compat.h"
	],
	"deps": null,
	"trimPrefixes": [],
	"cplusplus": false
}

```

**Comment by luoliwoshang** [comment]
根据日志，原因可能存在于 gnutls/compat.h 对于gnutls/gnutls.h的一个枚举类型，重新定义了一个相同的名字，但是相同的用例没有出现一样的问题

gnutls/gnutls.h
```
typedef enum gnutls_cipher_algorithm {
	GNUTLS_CIPHER_UNKNOWN = 0,
	GNUTLS_CIPHER_NULL = 1,
} gnutls_cipher_algorithm_t;
```
gnutls/compat.h 
```
typedef gnutls_cipher_algorithm_t gnutls_cipher_algorithm
	_GNUTLS_GCC_ATTR_DEPRECATED;
```

**Comment by luoliwoshang** [comment]
bdw-gc  redeclared 的问题也是因为目前gogensig的include处理逻辑为直接根据include决定转换顺序，目前的逻辑导致先转换了 cord_pos.h ，而后再转换cord.h,这导致了cord_pos 使用类型CORD时，还并不存在这个类型。

`cord_pos.h`
```
struct CORD_pe {
    CORD pe_cord;
    size_t pe_start_pos;
};
```
`cord.h`
```
typedef const char * CORD;
#include "cord_pos.h"
```


#### related llcppg.cfg
```
{
	"name": "bdw_gc",
	"cflags": "$(pkg-config --cflags bdw-gc)",
	"libs": "$(pkg-config --libs bdw-gc)",
	"include": [
		"gc/gc_inline.h",
		"gc_cpp.h",
		"gc/gc_backptr.h",
		"gc/gc_mark.h",
		"gc.h",
		"gc/leak_detector.h",
		"gc/javaxfc.h",
		"gc/gc_cpp.h",
		"gc/gc_disclaim.h",
		"gc/gc_gcj.h",
		"gc/gc_typed.h",
		"gc/gc.h",
		"gc/ec.h",
		"gc/cord.h",
		"gc/gc_pthread_redirects.h",
		"gc/gc_tiny_fl.h",
		"gc/gc_version.h",
		"gc/gc_config_macros.h",
		"gc/gc_allocator.h",
		"gc/cord_pos.h"
	],
	"deps": null,
	"trimPrefixes": [],
	"cplusplus": false
}
```

**Comment by luoliwoshang** [comment]
python-3.12-embed 相同的问题，先处理了`cpython/object.h`,再处理的`object.h`,导致使用`unaryfunc`类型时还不存在定义。


`object.h`
```
typedef PyObject * (*unaryfunc)(PyObject *);
include "cpython/object.h"
```
`cpython/object.h`
```
typedef struct {
    /* Number implementations must check *both*
       arguments for proper type and implement the necessary conversions
       in the slot functions themselves. */

    binaryfunc nb_add;
    binaryfunc nb_subtract;
    binaryfunc nb_multiply;
    binaryfunc nb_remainder;
    binaryfunc nb_divmod;
    ternaryfunc nb_power;
    unaryfunc nb_negative;
    unaryfunc nb_positive;
}
```
`llcppg.cfg`
```
{
	"name": "python_3_12_embed",
	"cflags": "$(pkg-config --cflags python-3.12-embed)",
	"libs": "$(pkg-config --libs python-3.12-embed)",
	"include": [
		"internal/pycore_blocks_output_buffer.h",
		"Python.h",
		"objimpl.h",
		"pymem.h",
		"frameobject.h",
		"pyport.h",
		"object.h",
		"pylifecycle.h",
		"ceval.h",
		"warnings.h",
		"tupleobject.h",
		"traceback.h",
		"sysmodule.h",
		"setobject.h",
		"pythonrun.h",
		"pystate.h",
		"descrobject.h",
		"complexobject.h",
		"dictobject.h",
		"pyframe.h",
		"pyerrors.h",
		"compile.h",
		"weakrefobject.h",
		"modsupport.h",
		"methodobject.h",
		"memoryobject.h",
		"longobject.h",
		"listobject.h",
		"interpreteridobject.h",
		"bytesobject.h",
		"internal/pycore_frame.h",
		"bytearrayobject.h",
		"import.h",
		"abstract.h",
		"floatobject.h",
		"fileutils.h",
		"fileobject.h",
		"internal/pycore_genobject.h",
		"internal/pycore_obmalloc.h",
		"internal/pycore_abstract.h",
		"internal/pycore_asdl.h",
		"internal/pycore_ast.h",
		"internal/pycore_ast_state.h",
		"internal/pycore_atexit.h",
		"internal/pycore_atomic.h",
		"internal/pycore_atomic_funcs.h",
		"internal/pycore_bitutils.h",
		"internal/pycore_bytes_methods.h",
		"internal/pycore_bytesobject.h",
		"internal/pycore_call.h",
		"internal/pycore_ceval.h",
		"internal/pycore_ceval_state.h",
		"internal/pycore_code.h",
		"internal/pycore_compile.h",
		"internal/pycore_condvar.h",
		"internal/pycore_context.h",
		"internal/pycore_descrobject.h",
		"internal/pycore_dict.h",
		"internal/pycore_dict_state.h",
		"internal/pycore_dtoa.h",
		"internal/pycore_emscripten_signal.h",
		"internal/pycore_exceptions.h",
		"internal/pycore_faulthandler.h",
		"internal/pycore_fileutils.h",
		"internal/pycore_fileutils_windows.h",
		"internal/pycore_floatobject.h",
		"internal/pycore_flowgraph.h",
		"internal/pycore_format.h",
		"internal/pycore_function.h",
		"internal/pycore_gc.h",
		"internal/pycore_getopt.h",
		"internal/pycore_gil.h",
		"internal/pycore_global_objects.h",
		"internal/pycore_global_objects_fini_generated.h",
		"internal/pycore_global_strings.h",
		"internal/pycore_hamt.h",
		"internal/pycore_hashtable.h",
		"internal/pycore_import.h",
		"internal/pycore_initconfig.h",
		"internal/pycore_instruments.h",
		"internal/pycore_interp.h",
		"internal/pycore_intrinsics.h",
		"internal/pycore_list.h",
		"internal/pycore_long.h",
		"internal/pycore_memoryobject.h",
		"internal/pycore_moduleobject.h",
		"internal/pycore_namespace.h",
		"internal/pycore_object.h",
		"internal/pycore_object_state.h",
		"internal/pycore_obmalloc_init.h",
		"internal/pycore_opcode.h",
		"internal/pycore_opcode_utils.h",
		"internal/pycore_parser.h",
		"internal/pycore_pathconfig.h",
		"internal/pycore_pyarena.h",
		"internal/pycore_pyerrors.h",
		"internal/pycore_pyhash.h",
		"internal/pycore_pylifecycle.h",
		"internal/pycore_pymath.h",
		"internal/pycore_pymem.h",
		"internal/pycore_pymem_init.h",
		"internal/pycore_pystate.h",
		"internal/pycore_pythread.h",
		"internal/pycore_range.h",
		"internal/pycore_runtime.h",
		"internal/pycore_runtime_init.h",
		"internal/pycore_runtime_init_generated.h",
		"internal/pycore_signal.h",
		"internal/pycore_sliceobject.h",
		"internal/pycore_strhex.h",
		"internal/pycore_structseq.h",
		"internal/pycore_symtable.h",
		"internal/pycore_sysmodule.h",
		"internal/pycore_time.h",
		"internal/pycore_token.h",
		"internal/pycore_traceback.h",
		"internal/pycore_tracemalloc.h",
		"internal/pycore_tuple.h",
		"internal/pycore_typeobject.h",
		"internal/pycore_typevarobject.h",
		"internal/pycore_ucnhash.h",
		"internal/pycore_unicodeobject.h",
		"internal/pycore_unicodeobject_generated.h",
		"internal/pycore_unionobject.h",
		"internal/pycore_warnings.h",
		"intrcheck.h",
		"iterobject.h",
		"marshal.h",
		"moduleobject.h",
		"opcode.h",
		"osdefs.h",
		"osmodule.h",
		"patchlevel.h",
		"py_curses.h",
		"pybuffer.h",
		"pycapsule.h",
		"pyconfig.h",
		"pydtrace.h",
		"pydtrace_probes.h",
		"pyexpat.h",
		"pyhash.h",
		"pymacconfig.h",
		"pymacro.h",
		"pymath.h",
		"pystats.h",
		"pystrcmp.h",
		"pystrtod.h",
		"pythread.h",
		"pytypedefs.h",
		"rangeobject.h",
		"sliceobject.h",
		"structmember.h",
		"structseq.h",
		"tracemalloc.h",
		"codecs.h",
		"typeslots.h",
		"unicodeobject.h",
		"boolobject.h",
		"bltinmodule.h"
	],
	"deps": null,
	"trimPrefixes": [],
	"cplusplus": false
}

```

**Comment by luoliwoshang** [comment]
openssl, libssl, libcrypto

`conf.h`
```c
struct conf_st;
struct conf_method_st;
typedef struct conf_method_st CONF_METHOD;
#  include <openssl/conftypes.h>
```
`conftype.h`
```
struct conf_method_st {
    const char *name;
    CONF *(*create) (CONF_METHOD *meth);
    int (*init) (CONF *conf);
    int (*destroy) (CONF *conf);
    int (*destroy_data) (CONF *conf);
    int (*load_bio) (CONF *conf, BIO *bp, long *eline);
    int (*dump) (const CONF *conf, BIO *bp);
    int (*is_number) (const CONF *conf, char c);
    int (*to_int) (const CONF *conf, char c);
    int (*load) (CONF *conf, const char *name, long *eline);
};

struct conf_st {
    CONF_METHOD *meth;
    void *meth_data;
    LHASH_OF(CONF_VALUE) *data;
    int flag_dollarid;
    int flag_abspath;
    char *includedir;
    OSSL_LIB_CTX *libctx;
};

```

**Comment by luoliwoshang** [comment]
> llcppgtest gnutls 
> llcppgtest gnutls-dane 
> llcppgtest libzstd 
> llcppgtest openssl
> 
> ```
> panic: underlying type must not be nil
> ```

libbzstd 的问题已在latest llcppg 中被修复

**Comment by luoliwoshang** [comment]
fixed in https://github.com/goplus/llcppg/pull/164
